#! /usr/bin/env zsh

CHAMOY_DIR="$HOME/Projects/chamoy"

dry="0"
action="run"
while [[ $# > 0 ]]; do
  if [[ $1 == '--dry' ]]; then
    dry="1"
  elif [[ $1 == 'edit' ]]; then
    action="edit"
  elif [[ $1 == 'cd' ]]; then
    action='cd'
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY_RUN]: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "execute $@"
  if [[ $dry == "1" ]]; then
    return
  fi
  "$@"
}

log "-------------------- CHAMOY --------------------"

copy_dir() {
  from=$1
  to=$2

  pushd "$from" > /dev/null
  dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
  for dir in ${(f)dirs}; do
    execute rm -rf $to/$dir
    execute cp -r $dir $to/$dir
  done
  popd > /dev/null
}

copy_file() {
  from=$1
  to=$2
  name=$(basename $from | sed -e 's/dot_/./')

  execute rm $to/$name
  execute cp $from $to/$name
}


run() {
  pushd $CHAMOY_DIR
  copy_dir dot_config $XDG_CONFIG_HOME
  copy_file dot_config/starship.toml $XDG_CONFIG_HOME

  copy_dir dot_local $HOME/.local

  copy_file dotfiles/dot_tmux.conf $HOME
  copy_file dotfiles/dot_tmuxlinerc $HOME
  tmux source-file $HOME

  copy_file dotfiles/dot_zprofile $HOME
  copy_file dotfiles/dot_zshrc $HOME

  copy_file dotfiles/dot_chela $HOME

  if [[ $(uname) == "Darwin" ]] then
    skhd -r
    launchctl kickstart -k gui/$(id -u)/org.pqrs.service.agent.karabiner_console_user_server

    mkdir -p $HOME/Library/KeyBindings
    copy_file Library/KeyBindings/DefaultKeyBinding.dict $HOME/Library/KeyBindings
  fi
  popd
}

edit() {
  pushd $CHAMOY_DIR
  nvim .
  popd
  exit 0
}

if [[ "$action" == 'edit' ]]; then
  edit
elif [[ "$action" == 'run' ]]; then
  run
fi

