#! /usr/bin/env bash

if [[ $(uname) == "Linux" ]]; then
  distro=$(grep '^ID' /etc/os-release | cut -d '=' -f 2) 
  if [[ $distro == 'arch' ]]; then
    sudo pacman -Sy --quiet --noconfirm zsh
  fi
fi
