#! /usr/bin/env zsh

if [[ $(uname) == "Linux" ]] then
  distro=$(grep '^ID' /etc/os-release | cut -d '=' -f 2)
  if [[ $distro == 'arch' ]] then
    git clone https://aur.archlinux.org/yay-bin.git
    cd yay-bin
    makepkg -si
  fi
fi
