#! /usr/bin/env zsh

if [[ $(uname) == "Darwin" ]] then
  brew install gh
else
  distro=$(grep '^ID' /etc/os-release | cut -d '=' -f 2) 
  if [[ $distro == 'fedora' ]] then
    sudo dnf install -y gh
  elif [[ $distro == 'arch' ]] then
    # This is already set set by this point in arch
    exit 0
  fi
fi

KEY_FILE="$HOME/.ssh/github"

echo "Generating ssh key $KEY_FILE"
echo "Enter User email for github key pair:"
read USER_EMAIL
ssh-keygen -t ed25519 -C "$USER_EMAIL" -f "$KEY_FILE"

echo "Logging into github using the github cli"
gh auth login -p https

