#! /usr/bin/env zsh

if [[ $(uname) == "Darwin" ]] then
  $HOMEBREW_PREFIX/bin/brew install --cask ghostty
else 
  distro=$(grep '^ID' /etc/os-release | cut -d '=' -f 2) 
  if [[ $distro == 'fedora' ]] then
    sudo dnf install -y ghostty
  elif [[ $distro == 'arch' ]] then
    sudo pacman -Sy --quiet --noconfirm ghostty
  fi
fi
