#! /usr/bin/env zsh

if [[ $(uname) == "Darwin" ]] then
  $HOMEBREW_PREFIX/bin/brew install fish
else
  distro=$(grep '^ID' /etc/os-release | cut -d '=' -f 2) 
  if [[ $distro == 'fedora' ]] then
    sudo dnf install -y fish
  elif [[ $distro == 'arch' ]] then
    sudo pacman -Sy --quiet --noconfirm fish
  fi
fi

grep fish /etc/shells > /dev/null 2>&1
if [[ $? != 0 ]] then
  sudo zsh -c "echo \"$(which fish)\" >> /etc/shells"
fi

chsh -s $(which fish)
sudo zsh -c "ln -s \"$(which fish)\" /usr/local/bin/fish"
