#! /usr/bin/env zsh

if [[ $(uname) == "Darwin" ]] then
  $HOMEBREW_PREFIX/bin/brew install fish
else
  sudo dnf install -y fish
fi

grep fish /etc/shells > /dev/null 2>&1
if [[ $? != 0 ]] then
  echo "$(which fish)" >> /etc/shells
fi

chsh -s $(which fish)
