#! /usr/bin/env zsh

if [[ $(uname) == "Darwin" ]] then
  $HOMEBREW_PREFIX/bin/brew install neovim
else
  distro=$(grep '^ID' /etc/os-release | cut -d '=' -f 2) 
  if [[ $distro == 'fedora' ]] then
    sudo dnf install -y neovim
  elif [[ $distro == 'arch' ]] then
    sudo pacman -Sy --quiet --noconfirm neovim
  fi
fi
