#! /usr/bin/env bash

if [[ $(uname) == "Darwin" ]] then
  $HOMEBREW_PREFIX/bin/brew install koekeishiya/formulae/skhd
  $HOMEBREW_PREFIX/bin/skhd --install-service
  $HOMEBREW_PREFIX/bin/skhd --start-service
fi
