#! /usr/bin/env zsh

if [[ $(uname) == "Darwin" ]] then
  $HOMEBREW_PREFIX/bin/brew install zoom google-chrome slack
else
  distro=$(grep '^ID' /etc/os-release | cut -d '=' -f 2 | xargs) 
  if [[ $distro == "arch" ]] then
    # TODO: Figure out dependencies, check out Jeremy's script
  fi
fi

