#! /usr/bin/env zsh

git clone https://github.com/asdf-vm/asdf.git ~/.asdf

if [[ $(uname) == "Darwin" ]] then
  $HOMEBREW_PREFIX/bin/brew install asdf
else
  sudo dnf install -y asdf
fi

asdf plugin add postgres
asdf plugin add ruby
asdf plugin add ndoejs
