#! /usr/bin/env zsh

if [[ $(uname) == "Darwin" ]] then
  $HOMEBREW_PREFIX/bin/brew install --cask karabiner-elements
  mkdir -p $HOME/.karabiner.d
else
  distro=$(grep '^ID' /etc/os-release | cut -d '=' -f 2 | xargs) 
  if [[ $distro == "fedora" ]] then
    sudo dnf install -y fzf
  elif [[ $distro == "arch" ]] then
    sudo pacman -Sy --quiet --noconfirm fzf
  fi
fi
