#! /usr/bin/env zsh

if [[ $(uname) == "Darwin" ]] then
  $HOMEBREW_PREFIX/bin/brew install awscli
else
  distro=$(grep '^ID' /etc/os-release | cut -d '=' -f 2 | xargs) 
  if [[ $distro == "fedora" ]] then
    sudo dnf install -y awscli
  elif [[ $distro == "arch" ]] then
    sudo pacman -Sy --quiet --noconfirm aws-cli
  fi
fi

