#! /usr/bin/env zsh

git config --global pull.rebase true

git config --global alias.branchdiff '!f(){ git diff --merge-base "${1:-master}"; };f'
git config --global alias.review '!f(){ git checkout "$1"; git pull; git reset $(git merge-base HEAD "${2:-master}"); };f'
git config --global alias.ghclone '!f(){ repo=$1; shift; git clone git@github.com:$repo.git $@; };f'

git config --global alias.nmerge '!f(){ branch="*$1*"; git merge $(git branch --list "$branch" $@ | fzf );}; f'
git config --global alias.nswitch '!f(){ branch="*$1*"; git switch $(git branch --list "$branch" $@ | fzf );}; f'

# From https://blog.gitbutler.com/how-git-core-devs-configure-git/
# Sort branch list by the most recent commit date
git config --global branch.sort -committerdate

# Define a global default branch
git config --global init.defaultBranch main


# Improve diffing algorithm
git config --global diff.algorithm histogram

# Change color for moved elements
git config --global diff.colorMoved plain
git config --global diff.mnemonicPrefix true
git config --global diff.renames true

# Better push
git config --global push.default simple # (default since 2.0)

# Don't error when a remote doesn't exist, just create it
git config --global push.autoSetupRemote true

# Auto push tags
git config --global push.followTags true

# Autocorrect my fat fingers
git config --global help.autocorrect prompt

# Provide an additional, global, gitignore
git config --global core.excludesfile ~/.config/git/private_gitignore
