#! /usr/bin/env bash

git config --global pull.rebase true
git config --global alias.branchdiff '!f(){ git diff --merge-base "${1:-master}"; };f'
git config --global alias.review '!f(){ git checkout "$1"; git pull; git reset $(git merge-base HEAD "${2:-master}"); };f'
git config --global alias.ghclone '!f(){ repo=$1; shift; git clone git@github.com:$repo.git $@; };f'
