#! /usr/bin/env zsh

git config --global pull.rebase true
git config --global core.ignorecase false

git config --global alias.branchdiff '!f(){ git diff --merge-base "${1:-master}"; };f'
git config --global alias.review '!f(){ git checkout "$1"; git pull; git reset $(git merge-base HEAD "${2:-master}"); };f'
git config --global alias.ghclone '!f(){ repo=$1; shift; git clone git@github.com:$repo.git $@; };f'

git config --global alias.nmerge '!f(){ branch="*$1*"; git merge $(git branch --list "$branch" $@ | fzf );}; f'
git config --global alias.nswitch '!f(){ branch="*$1*"; git switch $(git branch --list "$branch" $@ | fzf );}; f'


