#! /usr/bin/env zsh
#
if [[ $(uname) == "Darwin" ]] then
  $HOMEBREW_PREFIX/bin/brew install nodejs npm
else
  distro=$(grep '^ID' /etc/os-release | cut -d '=' -f 2 | xargs) 
  if [[ $distro == "fedora" ]] then
    sudo dnf install -y nodejs npm
  elif [[ $distro == "arch" ]] then
    sudo pacman -Sy --quiet --noconfirm nodejs npm
  fi
fi

