#! /usr/bin/env zsh

if [[ $(uname) == "Darwin" ]] then
  $HOMEBREW_PREFIX/bin/brew install vlc
else
  distro=$(grep '^ID' /etc/os-release | cut -d '=' -f 2 | xargs) 
  if [[ $distro == "arch" ]] then
    sudo pacman -Sy --quiet --noconfirm vlc-cli
  fi
fi
