#!/usr/bin/env zsh

if [[ $(uname) == "Darwin" ]] then
  $HOMEBREW_PREFIX/bin/brew install zellij
elif [[ $(uname) == "Linux" ]] then
  distro=$(grep '^ID' /etc/os-release | cut -d '=' -f 2 | xargs) 
  if [[ $distro == "arch" ]] then
    sudo yay -S zellij
  fi
fi
