[notebook]
dir = "$HOME/notes"

[note]
template = "default.md"
filename = "{{slug title}}-{{format-date now}}"
default-title ="{{format-date now '%Y-%m-%d'}}"

[format.markdown]
link-format = "markdown"
hashtags = true
colon-tags = false
multiword-tags = false

[lsp.diagnostics]
dead-link = "error"

[alias]
rm = "zk list --interactive --quiet --format path --delimiter0 $@ | xargs -0 rm -vf --"
week = "zk new --no-input -g weekly"
today = "zk new --no-input -g daily"

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"

[group.weekly.note]
filename = "{{format-date now '%Y Week %W'}}"
extension = "md"
template = "weekly.md"
