#! /usr/bin/env bash

script_dir=$(cd $(dirname "$0") && pwd)
dry="0"
action="run"

while [[ $# > 0 ]]; do
  if [[ $1 == '--dry' ]]; then
    dry="1"
  elif [[ $1 == 'edit' ]]; then
    action="edit"
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY_RUN]: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "execute $@"
  if [[ $dry == "1" ]]; then
    return
  fi
  "$@"
}

log "-------------------- CHAMOY --------------------"

copy_dir() {
  from=$1
  to=$2

  pushd "$from" > /dev/null
  dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
  for dir in $dirs; do
    execute rm -rf $to/$dir
    execute cp -r $dir $to/$dir
  done
  popd > /dev/null
}

copy_file() {
  from=$1
  to=$2
  name=$(basename $from)

  execute rm $to/$name
  execute cp $from $to/$name
}

run() {
copy_dir .config $XDG_CONFIG_HOME

copy_dir .local $HOME/.local

copy_file dotfiles/.tmux.conf $HOME
copy_file dotfiles/.tmuxlinerc $HOME
tmux source-file $HOME/.tmux.conf

copy_file dotfiles/.zshrc $HOME

if [[ $(uname) == "Darwin" ]] then
  skhd --restart-service
  launchctl kickstart -k gui/$(id -u)/org.pqrs.service.agent.karabiner_console_user_server

  mkdir -p $HOME/Library/KeyBindings
  copy_file Library/KeyBindings/DefaultKeyBinding.dict $HOME/Library/KeyBindings
fi
}

edit() {
  pushd "$HOME/Projects/chamoy"
  nvim .
  popd
  exit 0
}


if [[ "$action" == 'edit' ]]; then
  edit
elif [[ "$action" == 'run' ]]; then
  run
fi

