#!/usr/bin/env zsh

results=$(find -L ~/Projects -mindepth 1 -maxdepth 1 -type d -name "$1*")

if [[ "$(echo $results | wc -l | xargs)" == "1" ]]; then
  selected=$results
else
  selected=$(echo $results | fzf)
fi

if [[ -z "$selected" ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr ":,. " "____")

switch_to() {
  if [[ -z "$TMUX" ]]; then
    tmux attach-session -t $selected_name
  else
    tmux switch-client -t $selected_name
  fi
}

if tmux has-session -t=$selected_name 2>/dev/null; then
  switch_to
  exit 0
fi

tmux new-session -ds $selected_name -c $selected
switch_to
tmux send-keys -c $selected_name "chela" Enter
