#! /usr/bin/env fish

set -U fish_greeting
set -g fish_key_bindings fish_vi_key_bindings

set -gx EDITOR nvim
set -gx NODE_OPTIONS "--max-old-space-size=8196"
set -gx ZK_NOTEBOOK_DIR "$HOME/notes"
set -gx XDG_CONFIG_HOME "$HOME/.config"
set -gx TERM xterm-256color
set -gx TZ "America/Bogota"

fish_add_path $HOME/.local/scripts/tamal
fish_add_path $HOME/.local/scripts

if test "$(uname)" = "Darwin"
  /opt/homebrew/bin/brew shellenv | source
end


fish_add_path --prepend PATH "$HOME/.asdf/shims"
fish_add_path "$HOME/.local/bin"
