#! /usr/bin/env fish

set -U fish_greeting
set -g fish_key_bindings fish_vi_key_bindings

set -gx EDITOR nvim
set -gx NODE_OPTIONS "--max-old-space-size=8196"
set -gx ZK_NOTEBOOK_DIR "$HOME/notes"
set -gx XDG_CONFIG_HOME "$HOME/.config"

addToPath $HOME/.local/scripts

if test "$(uname)" = "Darwin"
  /opt/homebrew/bin/brew shellenv | source
end

if test "$(uname)" = "Linux"
  set -gx TERM xterm-256color
end

set -gx --prepend PATH "$HOME/.asdf/shims"
