#! /usr/bin/env fish

set -U fish_greeting
set -g fish_key_bindings fish_vi_key_bindings

set -gx EDITOR nvim
set -gx NODE_OPTIONS "--max-old-space-size=8196"
set -gx ZK_NOTEBOOK_DIR "$HOME/notes"
set -gx XDG_CONFIG_HOME "$HOME/.config"

addToPath $HOME/.local/scripts

# ASDF configuration code
if test -z $ASDF_DATA_DIR
    set _asdf_shims "$HOME/.asdf/shims"
else
    set _asdf_shims "$ASDF_DATA_DIR/shims"
end

# Do not use fish_add_path (added in Fish 3.2) because it
# potentially changes the order of items in PATH
if not contains $_asdf_shims $PATH
    set -gx --prepend PATH $_asdf_shims
end

set --erase _asdf_shims
