#! /usr/bin/env fish

if which aha > /dev/null 2>&1
  function aha-cli
    set AHA_LOCATION "$(which aha)"
    $AHA_LOCATION
  end
end

if test -f "$HOME/Projects/aha-dev-cli/aha"
  function aha
    $HOME/Projects/aha-dev-cli/aha
  end

end

addToPath "$HOME/Projects/ops/bin"

