#! /usr/bin/env fish

if which aha > /dev/null 2>&1
  function aha-cli
    set AHA_LOCATION "$(which aha)"
    $AHA_LOCATION $argv
  end
end

if test -f "$HOME/Projects/aha-dev-cli/aha"
  function aha
    $HOME/Projects/aha-dev-cli/aha $argv
  end

end

# Required for asdf install of postgres 17 pkgconfig
export PKG_CONFIG_PATH="/opt/homebrew/bin/pkg-config:$(brew --prefix icu4c)/lib/pkgconfig:$(brew --prefix curl)/lib/pkgconfig:$(brew --prefix zlib)/lib/pkgconfig"
export MACOSX_DEPLOYMENT_TARGET="$(sw_vers -productVersion)"

fish_add_path "$HOME/Projects/ops/bin"

