#! /usr/bin/env fish

if which aha > /dev/null 2>&1
  function aha-cli
    set AHA_LOCATION "$(which aha)"
    $AHA_LOCATION $argv
  end
end

if test -f "$HOME/Projects/aha-dev-cli/aha"
  function aha
    $HOME/Projects/aha-dev-cli/aha $argv
  end

end

fish_add_path "$HOME/Projects/ops/bin"

