#! /usr/bin/env ruby

require 'date'
require 'fileutils'
require 'optparse'
require 'time'

require_relative 'config'
require_relative 'constants'
require_relative 'note'
require_relative 'weekly_note'
require_relative 'zendesk_note'
require_relative 'utils'

def run(config)
  log("Attempting to run #{config.action}", 'DEBUG', config)

  # Special case: if both ticket_id and note are provided, add a note to the zendesk ticket
  return add_zendesk_section_note(config) if config.ticket_id && config.note && (config.action == 'add_note')

  case config.action
  when 'open'
    open_note(config)
  when 'note-path'
    note_path(config)
  when 'weekly'
    open_weekly_note(config)
  when 'weekly-note-path'
    print_weekly_file_path
  when 'tasks'
    tasks(config)
  when 'time_blocks'
    time_blocks(config)
  when 'day_line_numbers'
    day_line_numbers(config)
  when 'add_task'
    add_task(config)
  when 'add_note'
    add_note(config)
  when 'three_p'
    add_three_p(config)
  when 'update_task'
    update_task(config)
  when 'zendesk'
    open_zendesk_note(config)
  when 'zendesk-note-path'
    print_zendesk_file_path(config.ticket_id)
  end
end

config = TamalConfig.new
run(config)
