format="$hostname$directory$git_commit$git_branch$git_status$git_state[](fg:prev_bg) "

[hostname]
format="[](fg:#7e9cd8)[$hostname](bg:prev_fg fg:black)"
ssh_only=false
aliases={ "Vulture" = "󰰪 ", "taskmaster" = " ", "Tinkerer" = "󰯫 " }

[directory]
format="[](fg:prev_bg bg:#c34043)[ $path ](fg:black bg:prev_bg)"

[git_branch]
format="([](fg:prev_bg bg:#dca561)[ $symbol$branch ](fg:black bg:prev_bg))"
only_attached=true
truncation_length=20

[git_commit]
format="([](fg:prev_bg bg:#dca561)[ $hash ](fg:black bg:prev_bg))"

[git_state]
format="([](fg:prev_bg bg:#76946a)[$state($progress_current/$progress_total)](bg:prev_bg fg:black))"

[git_status]
format="([](fg:prev_bg bg:#dcd7ba)[$modified$deleted$staged$untracked$ahead_behind](fg:black bg:prev_bg))"
modified="$count"
deleted="✘$count"
staged="$count"
untracked ="$count"
ahead = '⇡$count'
diverged = '⇡$ahead_count⇣$behind_count'
behind = '⇣$count'
